### ISSUE TITLE
Revise the SimpleChallengeEnvironment to be compliant with current versions of gym (0.26.0)

### ISSUE THREAD

**Issue by slremy** [IBM/ushiriki-policy-engine-library#26]
**Describe the bug**
Gym requires spaces to inherit from "gym.spaces.Space"

**To Reproduce**
```
Python 3.8.9 (default, Apr 13 2022, 08:48:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> from ushiriki_policy_engine_library.SimpleChallengeEnvironment import ChallengeEnvironment
>>> env = gym.make("ushiriki_policy_engine_library:ChallengePolicy-v0", userID="61122946-1832-11ea-8d71-362b9e155667")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sekou/Library/Python/3.8/lib/python/site-packages/gym/envs/registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "/Users/sekou/Library/Python/3.8/lib/python/site-packages/gym/wrappers/env_checker.py", line 23, in __init__
    check_action_space(env.action_space)
  File "/Users/sekou/Library/Python/3.8/lib/python/site-packages/gym/utils/passive_env_checker.py", line 74, in check_space
    raise AssertionError(
AssertionError: action space does not inherit from `gym.spaces.Space`, actual type: <class 'ushiriki_policy_engine_library.SimpleChallengeEnvironment.mySpace'>
```
**Expected behavior**
Environment creation with no errors (or warnings)

**Desktop (please complete the following information):**
 - OSX
 - Version 12.4

**Additional context**
gym 0.26.0

**Comment by slremy** [comment]
Probably should consider switching to gymnasium.. and testing with https://github.com/thu-ml/tianshou, stable baselines, RL garage, and Popular RL.
